Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"

  # Переадресація порту 82 вгостьової машини на 8082 хост-машини
  config.vm.network "forwarded_port", guest: 82, host: 8082

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"  # Важливо: для запуску без KVM
    libvirt.memory = 1024
    libvirt.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Оновлення та встановлення nginx
    sudo apt update
    sudo apt install -y nginx

    # Заміна порту 80 на 82 у конфігурації nginx
    sudo sed -i 's/listen 80 default_server;/listen 82 default_server;/' /etc/nginx/sites-available/default
    sudo sed -i 's/listen \\[::\\]:80 default_server;/listen [::]:82 default_server;/' /etc/nginx/sites-available/default

    # Перезапуск nginx
    sudo systemctl restart nginx
  SHELL
end
